### ISSUE TITLE
Arachne Digital Community Call: A Walkthrough of Thread

### ISSUE THREAD

**Issue by twentysixmoons** [arachne-threat-intel/community#5]
# Arachne Digital Community Call: A Walkthrough of Thread
In this Community call, Arachne Digital will provide a walkthrough of the Thread software to do the following: 

1. Share how to download & login to the Thread platform 
2. Show how to use the Thread platform 
3. Provide context and a use case for the platform

**Arachne Digital hosts Community calls to:** 

1. Provide opportunities to build connections with contributors and the larger open-source ecosystem
2. Share information on how the technology and surrounding systems of support work 
3. Foster support for Arachne open-source projects and collaborators 

## 📝 Pre-event 
It's recommended this occurs 2 weeks prior. These are things to complete before sharing our event publicly 
- [x] @twentysixmoons Complete an event brief describing the community call's goal ([View it here](https://docs.google.com/document/d/1TzFyYBSmH4qCmNk2NGI26mkv5x5R-48DvurTbZknM6o/edit?usp=sharing))
- [x] @twentysixmoons Create an event graphic with the title, time, and date
- [x] @KadeMorton & @jecarr Approvals from Arachne Digital Team 

## 📣 Event Promotion
This should begin around 2-1 weeks before event start. 
- [x] @twentysixmoons Create the event invitation link on Eventbrite 
- [x] @twentysixmoons Create blog/medium post invitation blog post
- [x] @KadeMorton approval for blog post
- [x] @KadeMorton Create a social post on LinkedIn
- [x] @twentysixmoons Share in Slack 
- [x] @twentysixmoons Share in Email 
- [x] @twentysixmoons Share on Linkedin 
- [x] @twentysixmoons Share in aligned organizations Slacks & Discords 

## ✨ Event Prep 
This should be completed 1 week prior to the event star. 
- [x] @twentysixmoons Create event slides 
- [x] @twentysixmoons Event Reminder
~- [ ] @twentysixmoons Create event feedback form~

## 💫 Post-Event 
This should occur up to 1 week after the event ends. 
- [x] @twentysixmoons Post recording on Youtube
- [x] @twentysixmoons Share post-event materials to attendees and RSVPd people via email 
- [x] @twentysixmoons Post event slides in Github 
- [x] @twentysixmoons Post event write up on arachne.digital website 
- [x] @twentysixmoons Share overview on LinkedIn

**Comment by KadeMorton** [comment]
Absolutely fine to push it back a little. 

For downloading Thread, we might need to get a little video from Jenine as downloading and running locally is a bit of work, I just use the web version. Otherwise happy with the content.

For images, I've shared a the stock images folder with you.

**Comment by jecarr** [comment]
> For downloading Thread, we might need to get a little video from Jenine as downloading and running locally is a bit of work

Yea happy to do that - got a preferred time limit on how long to keep the video to?

**Comment by twentysixmoons** [comment]
Thanks @KadeMorton for the image access. I was able to use them for this graphic we'll review today: 
https://new.express.adobe.com/id/urn:aaid:sc:US:4aabb7ae-a884-59f4-96c8-2a0de4333280?invite=true&promoid=Z2G1FQKR&mv=other

@jecarr I'm working on updating the outline right now and will circle back on this by EOD (my time lol)

**Comment by KadeMorton** [comment]
@jecarr can we do a video that is less than ten minutes? We've got a max 10 minute slot but as short as we can make it would be ideal. @twentysixmoons also mentioned they can help with video editing.

**Comment by twentysixmoons** [comment]
The event page is live! Find it here: 
https://www.eventbrite.com/e/open-source-cyber-security-a-walkthrough-of-thread-tickets-1077688488279?aff=oddtdtcreator

@jecarr, I discussed with @KadeMorton that we have ten minutes for your video. I can help to edit it down if needed. Let me know if this works! 

The full planning brief is here for review: 
https://docs.google.com/document/d/1TzFyYBSmH4qCmNk2NGI26mkv5x5R-48DvurTbZknM6o/edit?usp=sharing

**Comment by twentysixmoons** [comment]
An invitation blog post is available to be published + shared on LinkedIn. Once Posted I'll share in a few channels I'm in: 
https://medium.com/@arachnedigital/your-invited-%EF%B8%8F-open-source-cyber-security-a-walkthrough-of-thread-1de3e3968158

**Comment by KadeMorton** [comment]
@twentysixmoons I've published the post so please spread the word!

**Comment by jecarr** [comment]
Thanks for the updates - I'll whip something up end of my week and I'll send it to you when it's ready 👍🏾

**Comment by twentysixmoons** [comment]
Shared on LinkedIn and in these spaces: 
- DISARM Slack 
- OpenSSF Slack 
- Hack for LA Slack 
- Open Austin Slack 
- Messaged Tech for Good founder to get it placed on their site

**Comment by twentysixmoons** [comment]
Sent an email to folks who joined our last event or expressed interests in getting emails on our Slack Jotform.

**Comment by twentysixmoons** [comment]
Working on the slides here: https://docs.google.com/presentation/d/1Zb20RRAmpL_7wqBvhbJcY4OfunG2DXWXyDTs6OSmFyc/edit?usp=drive_link

**Comment by twentysixmoons** [comment]
@KadeMorton for the event feedback forms, we should do those in Jotform also, right?

**Comment by twentysixmoons** [comment]
Sent a follow-up email: 

> Hello 👋🏼.
> 
> Thanks for hanging tight for our event follow-up. If you were able to join us, thank you! If you missed out, no worries. We hope we can see you next time or online.  
> 
> Find our links and resources from the event below 👇🏼: 
> View the [presentation slides](https://docs.google.com/presentation/d/1Zb20RRAmpL_7wqBvhbJcY4OfunG2DXWXyDTs6OSmFyc/edit?usp=sharing) + [recording on Youtube ](https://youtu.be/nRpuYn8jFvk?feature=shared)
> [Join us on slack](https://form.jotform.com/Arachne/request-for-slack-invitation)
> Find us on [Github](https://github.com/arachne-threat-intel) 
> [Threads](https://github.com/arachne-threat-intel/thread/) - The Github repository we covered
> [Community repository](https://github.com/arachne-threat-intel/community) - More about contributing with Arachne
> Follow us on [Bluesky](https://bsky.app/profile/arachnedigital.bsky.social) & [LinkedIn ](https://www.linkedin.com/company/arachne-digital/?viewAsMember=true)
> 
> Please reach out here or say hey in Slack if you have any questions.

Missed a few things on our checklist I'll work to get sorted for next time: 
- event feedback 
- updated process (Youtubing the video takes a little longer and has some nuance I wasn't ready for. I created #10 to review this and will need to look over #7 also. 

I'll add a couple of estimated time requirements to each of the checklist sections so I can plan better. As we move forward, it should get faster and more streamlined.

**Comment by twentysixmoons** [comment]
Making another note  here that some sort of metrics and check in process would be helpful for analytics for the post event wrap-up. 

Could include: 
- number of views of event page
- Number of RSVPs
- Number of attended
- Number of actions taken (joined our slack, responded to/opened an issue, others?)

**Comment by KadeMorton** [comment]
@twentysixmoons Sorry for the slow response, yes happy for jotforms to be used for event feedback forms. Happy to add whatever metrics you think will be useful.

**Comment by twentysixmoons** [comment]
Since some time has passed I combined the writeup for this one and and last community call. It's ready for review here: 
https://docs.google.com/document/d/1pv49SjwPZBn4P9hGdWzmIo_KGBWt6LrwZ20HZXk9Kbk/edit?usp=sharing

It's written in a way we can share it before the end of December or make slight adjustments for an early January share. 

@KadeMorton if you could review it that would be great.

**Comment by KadeMorton** [comment]
@twentysixmoons I've reviewed and it looks good, happy for this to go up!

**Comment by twentysixmoons** [comment]
published on Medium:
https://arachnedigital.medium.com/community-call-recap-cyber-security-open-source-and-thread-5d7f6dce366a

Ready to be shared on social then in slack

**Comment by KadeMorton** [comment]
@twentysixmoons I've scheduled the LinkedIn post, posted on Bluesky and in the community building chat in Slack.
