### ISSUE TITLE
Open source & Cyber Security Blog Post

### ISSUE THREAD

**Issue by twentysixmoons** [arachne-threat-intel/community#9]
First *issue* for a blog post. Sharing a template below for the process for a general blog post versus one for a "Meet the Team post". I'll need to place these checklist templates somewhere though and may be useful for folks that want to make non-code contributions. 🤔

### **Blog post process**
- [x] Create a blog post draft - (Should provide a template for this)
- [x] Share post for editorial  
- [x] Post to Medium/ Arachne.digital site
- [x] Share on LinkedIn 
- [x] Share on Blueksy 
- [x] Share in Slack
- [x] Add to the asset tracker: [Community Management Asset Tracker](https://docs.google.com/spreadsheets/d/1ySd2fpzeux8Dgp2DyWTAExksc6htTSxYB8fiu6q6T48/edit?usp=sharing)

**Comment by twentysixmoons** [comment]
Work-in-progress recap post here: 
https://docs.google.com/document/d/1pv49SjwPZBn4P9hGdWzmIo_KGBWt6LrwZ20HZXk9Kbk/edit?usp=sharing

**Comment by twentysixmoons** [comment]
Issue #5 has a combined recap for our first two calls that is ready for review.

**Comment by twentysixmoons** [comment]
published on Medium: 
https://arachnedigital.medium.com/community-call-recap-cyber-security-open-source-and-thread-5d7f6dce366a

Ready to be shared on social then in slack

**Comment by KadeMorton** [comment]
@twentysixmoons I've scheduled the LinkedIn post and I've posted on Bluesky.
